Refactor big and small datas handling
tdspora/syngen pull request #250
Opened 2023-08-14 13:02 UTC by pbobyrev

2023-08-14 15:43 UTC, Anna050689 requested changes

2023-08-14 15:43 UTC, Anna050689 commented on src/tests/unit/utils/test_utils.py
> +        #("2023-01-01 00:00:00", 1672527600.0),
Please, uncomment these lines.

2023-08-14 15:43 UTC, Anna050689 commented on src/syngen/ml/utils/utils.py
> +        elif int(year) < 1:
Should we use the same value as in min_allowed_time_ms?

2023-08-14 23:47 UTC, tdspora approved these changes
LGTM

2023-08-14 23:47 UTC, tdspora commented on src/syngen/ml/utils/utils.py
> +        return datetime(1, 1, 1, 0, 0, 0, 0)
Added the limits to https://kb.epam.com/display/EPMCTDM/Known+Issues

2023-08-15 07:25 UTC, Anna050689 approved these changes

2023-08-15 09:00 UTC, merged