Mlflow integration
tdspora/syngen pull request #273
Opened 2023-09-15 10:15 UTC by pbobyrev

2023-09-19 10:40 UTC, pbobyrev commented on src/syngen/ml/mlflow/mlflow_tracker.py
> +            print("IT IS ACTIVE")
I deleted it instead

2023-09-19 10:40 UTC, pbobyrev commented on src/syngen/ml/mlflow/mlflow_tracker.py
> +        print("START RUN IS RUNNNING")
I deleted it instead

2023-09-19 11:34 UTC, pbobyrev commented on src/syngen/ml/metrics/accuracy_test/accuracy_test.py
> +        tracker = MlflowTracker()
Is it feasible to make a one-line method?

2023-09-19 11:37 UTC, pbobyrev commented on src/syngen/infer.py
> +    set_mlflow(mlflow_exp_name)
Do we have access to the cli-passed variables "metadata_path" and "table_name" outside of the "launch_infer()" method?

2023-09-20 09:07 UTC, Anna050689 requested changes

2023-09-20 09:07 UTC, Anna050689 commented on src/syngen/ml/mlflow/mlflow_tracker.py
> +            metadata_name = experiment_name[:-20]  # strip datetime
This operation of indexing might cause an error.

2023-09-20 09:07 UTC, Anna050689 commented on src/syngen/ml/utils/utils.py
> +def fetch_unique_root(table_name: str, metadata_path: str):
Please, add the docstring here

2023-09-20 09:07 UTC, Anna050689 commented on src/syngen/ml/utils/utils.py
> +        response = os.system("ping -c 1 " + os.environ.get("MLFLOW_TRACKING_URI")[7:-6])
Is it possible to reduce the process of indexing "ML_FLOW_TRACKING_URL"?

2023-09-20 14:54 UTC, Anna050689 approved these changes

2023-10-20 16:03 UTC, merged