changed early stopping criteria from absolute to relative
tdspora/syngen pull request #360
Opened 2024-01-19 10:02 UTC by Ijka

changed early stopping criteria from absolute to relative

2024-01-24 15:52 UTC, rioman requested changes

2024-01-24 16:00 UTC, Ijka commented on src/syngen/ml/vae/wrappers/wrappers.py
> +        es_patience = 10
es = early_stopping

2024-01-24 16:08 UTC, rioman approved these changes

2024-02-09 10:14 UTC, closed without merging

2024-02-09 10:15 UTC, Ijka commented
will not be implemented now